import { Download, FileJson, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ThreatIntelligenceResult } from "@/types/threat-intelligence";

interface ExportButtonProps {
    data: ThreatIntelligenceResult;
}

export function ExportButton({ data }: ExportButtonProps) {
    const exportJSON = () => {
        const jsonString = JSON.stringify(data, null, 2);
        const blob = new Blob([jsonString], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `threat-report-${data.query}-${new Date().toISOString().split('T')[0]}.json`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const exportPDF = () => {
        const doc = new jsPDF();
        const timestamp = new Date().toLocaleString();

        // Title
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text("ThreatSumm4ry Report", 14, 22);

        // Header Info
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Target: ${data.query}`, 14, 32);
        doc.text(`Date: ${timestamp}`, 14, 38);
        doc.text(`Threat Level: ${data.threatLevel.toUpperCase()}`, 14, 44);
        doc.text(`Score: ${data.overallScore}/100`, 14, 50);

        // Vendor Summary Table
        const tableData = data.vendorData
            .filter(v => Object.keys(v.data).length > 0)
            .map(v => {
                // Extract a summary string from the data
                const summary = Object.entries(v.data)
                    .slice(0, 3)
                    .map(([key, val]) => `${key}: ${val}`)
                    .join("\n");
                return [v.name, summary];
            });

        autoTable(doc, {
            startY: 60,
            head: [["Vendor", "Findings"]],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
            styles: { fontSize: 10, cellPadding: 4 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' }
            }
        });

        // Footer
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(`Page ${i} of ${pageCount} - Generated by ThreatSumm4ry`, 14, doc.internal.pageSize.height - 10);
        }

        doc.save(`threat-report-${data.query}.pdf`);
    };

    return (
        <DropdownMenu>
            <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm" className="gap-2">
                    <Download className="h-4 w-4" />
                    Export Report
                </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={exportPDF}>
                    <FileText className="mr-2 h-4 w-4" />
                    Download PDF
                </DropdownMenuItem>
                <DropdownMenuItem onClick={exportJSON}>
                    <FileJson className="mr-2 h-4 w-4" />
                    Download JSON
                </DropdownMenuItem>
            </DropdownMenuContent>
        </DropdownMenu>
    );
}
