import { Button } from "@/components/ui/button";
import { Copy, Download, RefreshCw, Share2, Zap, FileJson, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { ThreatIntelligenceResult } from "@/types/threat-intelligence";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface QuickActionsProps {
  data: ThreatIntelligenceResult | null;
  onRefresh: () => void | Promise<void>;
  isLoading: boolean;
  onCopyLinks: () => void;
  onExport?: () => void; // Optional now as handled internally
}

export const QuickActions = ({ data, onRefresh, isLoading, onCopyLinks }: QuickActionsProps) => {
  const { toast } = useToast();

  const handleShare = () => {
    if (!data) return;

    const shareText = `Threat Analysis for ${data.query}\nThreat Level: ${data.threatLevel.toUpperCase()}\nScore: ${data.overallScore}%\nDetections: ${data.detections}/${data.totalVendors}`;

    if (navigator.share) {
      navigator.share({
        title: `ThreatSumm4ry - ${data.query}`,
        text: shareText,
      }).catch(() => {
        // Fallback to clipboard
        navigator.clipboard.writeText(shareText);
        toast({
          title: "Copied to clipboard",
          description: "Share link copied to clipboard",
        });
      });
    } else {
      navigator.clipboard.writeText(shareText);
      toast({
        title: "Copied to clipboard",
        description: "Analysis summary copied to clipboard",
      });
    }
  };

  const handleQuickRefresh = () => {
    toast({
      title: "Refreshing...",
      description: "Fetching latest threat intelligence data",
    });
    onRefresh();
  };

  const exportJSON = () => {
    if (!data) return;
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `threat-report-${data.query}-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportPDF = () => {
    if (!data) return;
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("ThreatSumm4ry Report", 14, 22);

    // Header Info
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Target: ${data.query}`, 14, 32);
    doc.text(`Date: ${timestamp}`, 14, 38);
    doc.text(`Threat Level: ${data.threatLevel.toUpperCase()}`, 14, 44);
    doc.text(`Score: ${data.overallScore}/100`, 14, 50);

    // Vendor Summary Table
    const tableData = data.vendorData
      .filter(v => Object.keys(v.data).length > 0)
      .map(v => {
        // Extract a summary string from the data
        const summary = Object.entries(v.data)
          .slice(0, 3)
          .map(([key, val]) => `${key}: ${val}`)
          .join("\n");
        return [v.name, summary];
      });

    autoTable(doc, {
      startY: 60,
      head: [["Vendor", "Findings"]],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [66, 66, 66] },
      styles: { fontSize: 10, cellPadding: 4 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 'auto' }
      }
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount} - Generated by ThreatSumm4ry`, 14, doc.internal.pageSize.height - 10);
    }

    doc.save(`threat-report-${data.query}.pdf`);
  };

  return (
    <div className="flex flex-wrap gap-2 animate-fade-in">
      <Button
        variant="outline"
        size="sm"
        onClick={handleQuickRefresh}
        disabled={isLoading || !data}
        className="gap-2 hover-scale"
      >
        <RefreshCw className={`h-4 w-4 ${isLoading ? "animate-spin" : ""}`} />
        Refresh
      </Button>

      <Button
        variant="outline"
        size="sm"
        onClick={onCopyLinks}
        disabled={!data}
        className="gap-2 hover-scale"
      >
        <Copy className="h-4 w-4" />
        Copy Links
      </Button>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            disabled={!data}
            className="gap-2 hover-scale"
          >
            <Download className="h-4 w-4" />
            Export
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={exportPDF}>
            <FileText className="mr-2 h-4 w-4" />
            Download PDF
          </DropdownMenuItem>
          <DropdownMenuItem onClick={exportJSON}>
            <FileJson className="mr-2 h-4 w-4" />
            Download JSON
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <Button
        variant="outline"
        size="sm"
        onClick={handleShare}
        disabled={!data}
        className="gap-2 hover-scale"
      >
        <Share2 className="h-4 w-4" />
        Share
      </Button>

      {data && (
        <div className="ml-auto flex items-center gap-2 text-sm text-muted-foreground">
          <Zap className="h-4 w-4" />
          <span>Quick Actions</span>
        </div>
      )}
    </div>
  );
};
